url: http://www.cloudworkshop.ieeebangalore.org/
baseurl: 

# Site settings
title: 
email: rajathkumar.exe@gmail.com
description: "Cloud Computing promises to be the “next big thing” in IT infrastructure and is poised to enable the next generation computing framework for the emerging markets. Cloud Computing is gaining great prominence all around the world, and even more so in emerging markets which are looking to leapfrog into the era of cloud and have great potential for leadership. India is one such emerging market which is looking to transform the nation through cloud services."
# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: IIIT Bangalore
  pic: 
  position:
  social:
    - title: plus
      url: #portfolioModal100

- name: Registration Details
  pic: 
  position:
  social:
    - title: plus
      url: #portfolioModal200
- name: FAQ
  pic: 
  position:
  social:
    - title: plus
      url: #portfolioModal300


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com
  - title: facebook
    url:

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty