url: http://rajathkumarmp.github.io
baseurl: /ieee-cloudcomputing/

# Site settings
title: 
email: rajathkumar.exe@gmail.com
description: "Cloud Computing promises to be the “next big thing” in IT infrastructure and is poised to enable the next generation computing framework for the emerging markets. Cloud Computing is gaining great prominence all around the world, and even more so in emerging markets which are looking to leapfrog into the era of cloud and have great potential for leadership. India is one such emerging market which is looking to transform the nation through cloud services."
# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Dinakar Sitaram
  pic: 
  position: Professor & Director, Cloud Center; Department of Computer Science and Engineering, PES University
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Dr. Pallabh Saha
  pic: 
  position: Partner, Chief Enterprise Architect (Government) & Head of Wipro Academy of Enterprise Architecture
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #      

- name: Emmanuel Pilli
  pic: 
  position: Assistant Professor at Malaviya National Institute of Technology, Jaipur
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Gita Manjunath
  pic: 
  position: Research Lab Manager at Xerox Research Centre India
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Pamela Kumar
  pic: 
  position: Vice President, Cloud Computing Innovation Council of India
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Lalith Mohan Sangavarapa
  pic: 
  position: Sr Technology Manager at Institute for Development and Research in Banking Technology
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Manoj Kumar Jain
  pic: 
  position: Sr. Technical Consultant at EMC2
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Krishna M Kumar
  pic: 
  position: Cloud Platforms Architect - Huawei Technologies
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Rohan Joshi
  pic: 
  position: Founder at Wolken Software Private Limited
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Saksham Khandelwal
  pic: 
  position: Senior Executive - Innovation at Wipro Ltd.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Sandeep Dhar
  pic: 
  position: Principal Engineer - Cisco Systems
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Srinivas Varadarajan
  pic: 
  position: Founder-CEO Vigyanlabs, Mentor at Founder Institute
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Swapnil Kulkarni
  pic: 
  position: Senior Software Engineer - Openstack at Red Hat
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Vibhakar Bhushan
  pic: 
  position: Chair - eHealth Working Group at Cloud Computing Innovation Council of India
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com
  - title: facebook
    url:

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty